[package]
name = "longest-strand"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
debug = false
panic = "abort"
overflow-checks = false

[dependencies]
crossbeam = "0.8.2"
rayon = "1.6.1"
